version: '3.7'

services:
  api:
    build:
      context: ./api
      dockerfile: docker/Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 80
    ports:
      - 80:80
    env_file:
      - .dev.env